[package]
name = "Image-Encryption-System"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.0.0-beta.2", features = ["yaml"] }
aes-gcm = "0.9.2"

[[bin]]
name = "Image-Encryption-System"
path = "main.rs"
